$script:ReportRoot=Join-Path (Join-Path $env:LOCALAPPDATA 'IIS-SMTP-Badmail-Analyzer') 'Reports'
$script:ArchiveRoot=Join-Path (Join-Path $env:LOCALAPPDATA 'IIS-SMTP-Badmail-Analyzer') 'Archives'
@($script:ReportRoot,$script:ArchiveRoot)|ForEach-Object{if(-not(Test-Path $_)){New-Item -ItemType Directory -Path $_ -Force|Out-Null}}
function Export-AnalyzerReport {param([object[]]$Rows,[string]$Server,[string]$BadmailPath)
 $stamp=Get-Date -Format 'yyyyMMdd_HHmmss';$safe=$Server -replace '[^A-Za-z0-9._-]','_';$html=Join-Path $script:ReportRoot ('SMTP-Badmail-Report_'+$safe+'_'+$stamp+'.html');$csv=[IO.Path]::ChangeExtension($html,'.csv')
 $e=[Net.WebUtility];$sb=New-Object Text.StringBuilder
 [void]$sb.Append("<!doctype html><meta charset='utf-8'><title>IIS SMTP Badmail Analyzer</title><style>body{font-family:Segoe UI,Arial;margin:32px;color:#202124}h1,h2{color:#17365d}table{border-collapse:collapse;width:100%}th,td{border:1px solid #d0d7de;padding:7px;vertical-align:top}th{background:#f3f6f9}.FAIL{color:#a40000;font-weight:600}.WARNING{color:#8a5a00;font-weight:600}</style><h1>IIS SMTP Badmail Analyzer</h1>")
 [void]$sb.Append('<p><b>SMTP server:</b> '+$e::HtmlEncode($Server)+'<br><b>Badmail:</b> '+$e::HtmlEncode($BadmailPath)+'<br><b>Generated:</b> '+(Get-Date)+'</p>')
 [void]$sb.Append('<h2>Executive Summary</h2><p>Messages: '+$Rows.Count+' | Unique failed recipients: '+@($Rows.FailedRecipient|Where-Object {$_}|Sort-Object -Unique).Count+'</p>')
 [void]$sb.Append('<h2>Findings and Remediation</h2><table><tr><th>Date</th><th>Severity</th><th>Source</th><th>Recipient</th><th>Category</th><th>AD</th><th>EXO</th><th>Evidence</th><th>Remediation</th></tr>')
 foreach($r in $Rows|Sort-Object Date -Descending){$ev=($r.Diagnostic,$r.SecondaryDiagnostic|Where-Object {$_}) -join ' | ';[void]$sb.Append('<tr><td>'+$r.Date+'</td><td class="'+$r.Severity+'">'+$r.Severity+'</td><td>'+$e::HtmlEncode([string]$r.Source)+'</td><td>'+$e::HtmlEncode([string]$r.FailedRecipient)+'</td><td>'+$e::HtmlEncode($r.Category)+'</td><td>'+$r.ADStatus+'</td><td>'+$r.EXOStatus+'</td><td>'+$e::HtmlEncode($ev)+'</td><td>'+$e::HtmlEncode($r.Remediation)+'</td></tr>')}
 [void]$sb.Append('</table><p>Not Checked means directory validation was not performed. It does not mean the recipient is absent.</p>');[IO.File]::WriteAllText($html,$sb.ToString(),[Text.Encoding]::UTF8);$Rows|Export-Csv $csv -NoTypeInformation -Encoding UTF8;[pscustomobject]@{Html=$html;Csv=$csv}
}
function New-BadmailArchive {param([string]$BadmailPath,[string]$Server);Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=Join-Path $script:ArchiveRoot (($Server -replace '[^A-Za-z0-9._-]','_')+'_Badmail_'+(Get-Date -Format 'yyyyMMdd_HHmmss')+'.zip');$stage=Join-Path $env:TEMP ('Badmail_'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory $stage|Out-Null;try{Get-ChildItem $BadmailPath -File|Where-Object Extension -in '.BAD','.BDR','.BDP'|Copy-Item -Destination $stage;[IO.Compression.ZipFile]::CreateFromDirectory($stage,$zip)}finally{Remove-Item $stage -Recurse -Force -ErrorAction SilentlyContinue};$zip}
Export-ModuleMember -Function Export-AnalyzerReport,New-BadmailArchive