#requires -Version 5.1
Add-Type -AssemblyName PresentationFramework
Add-Type -AssemblyName System.Windows.Forms
$here=Split-Path -Parent $MyInvocation.MyCommand.Path
Import-Module (Join-Path $here 'Modules\Analyzer.Core.psm1') -Force
Import-Module (Join-Path $here 'Modules\Analyzer.Parser.psm1') -Force
Import-Module (Join-Path $here 'Modules\Analyzer.Validation.psm1') -Force
Import-Module (Join-Path $here 'Modules\Analyzer.Report.psm1') -Force
$script:Rows=@();$script:Badmail=$null;$script:Server=$null;$script:Credential=$null
[xml]$x=@'
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" Title="IIS SMTP Badmail Analyzer" Height="780" Width="1250" WindowStartupLocation="CenterScreen">
<Grid Margin="12"><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="*"/><RowDefinition Height="Auto"/></Grid.RowDefinitions>
<StackPanel><TextBlock Text="IIS SMTP Badmail Analyzer" FontSize="24" FontWeight="SemiBold"/><TextBlock Text="Discovery, Badmail analysis, recipient validation, and remediation reporting" Foreground="DimGray" Margin="0,2,0,10"/></StackPanel>
<TabControl Grid.Row="1" Name="Tabs">
<TabItem Header="Setup"><Grid Margin="10"><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="Auto"/><RowDefinition Height="*"/></Grid.RowDefinitions>
<Grid><Grid.ColumnDefinitions><ColumnDefinition Width="Auto"/><ColumnDefinition Width="*"/><ColumnDefinition Width="Auto"/></Grid.ColumnDefinitions><Grid.RowDefinitions><RowDefinition/><RowDefinition/><RowDefinition/></Grid.RowDefinitions>
<TextBlock Text="SMTP server" Margin="5"/><TextBox Name="Server" Grid.Column="1" Margin="5"/><Button Name="Discover" Grid.Column="2" Margin="5" Padding="14,5" Content="Discover Mailroot"/>
<TextBlock Grid.Row="1" Text="Badmail path" Margin="5"/><TextBox Name="Path" Grid.Row="1" Grid.Column="1" Margin="5"/><Button Name="Browse" Grid.Row="1" Grid.Column="2" Margin="5" Padding="14,5" Content="Browse"/>
<CheckBox Name="AltCred" Grid.Row="2" Grid.Column="1" Margin="5" Content="Use alternate Windows credentials"/></Grid>
<GroupBox Header="Prerequisites" Grid.Row="1" Margin="0,10"><StackPanel><DataGrid Name="Prereq" Height="190" AutoGenerateColumns="True" IsReadOnly="True"/><StackPanel Orientation="Horizontal"><Button Name="RefreshPre" Content="Refresh" Margin="5" Padding="14,5"/><Button Name="InstallPre" Content="Install Selected" Margin="5" Padding="14,5"/></StackPanel></StackPanel></GroupBox>
<TextBlock Grid.Row="2" TextWrapping="Wrap" Text="Analysis is read-only. Optional requirements are never installed silently. Credentials remain in memory only."/></Grid></TabItem>
<TabItem Header="Analysis"><Grid Margin="8"><Grid.RowDefinitions><RowDefinition Height="Auto"/><RowDefinition Height="*"/><RowDefinition Height="Auto"/></Grid.RowDefinitions><StackPanel Orientation="Horizontal"><Button Name="Analyze" Content="Analyze Badmail" Margin="4" Padding="14,6"/><Button Name="AD" Content="Validate AD" Margin="4" Padding="14,6"/><Button Name="EXO" Content="Validate Exchange Online" Margin="4" Padding="14,6"/></StackPanel><DataGrid Name="Results" Grid.Row="1" Margin="4" AutoGenerateColumns="True" IsReadOnly="True"/><TextBlock Name="Summary" Grid.Row="2" Margin="4" FontWeight="SemiBold"/></Grid></TabItem>
<TabItem Header="Remediation"><DataGrid Name="Remediation" Margin="8" AutoGenerateColumns="False" IsReadOnly="True"><DataGrid.Columns><DataGridTextColumn Header="Recipient" Binding="{Binding FailedRecipient}" Width="190"/><DataGridTextColumn Header="Category" Binding="{Binding Category}" Width="170"/><DataGridTextColumn Header="AD" Binding="{Binding ADStatus}" Width="100"/><DataGridTextColumn Header="EXO" Binding="{Binding EXOStatus}" Width="100"/><DataGridTextColumn Header="Recommended remediation" Binding="{Binding Remediation}" Width="*"/></DataGrid.Columns></DataGrid></TabItem>
<TabItem Header="Reports / Archive"><StackPanel Margin="12"><Button Name="Report" Content="Export HTML + CSV Report" Width="240" Padding="10" Margin="4" HorizontalAlignment="Left"/><Button Name="Archive" Content="Archive Badmail (No Delete)" Width="240" Padding="10" Margin="4" HorizontalAlignment="Left"/><TextBlock Name="Output" Margin="4,12" TextWrapping="Wrap"/></StackPanel></TabItem>
</TabControl><StatusBar Grid.Row="2"><StatusBarItem><TextBlock Name="Status" Text="Ready"/></StatusBarItem><Separator/><StatusBarItem><TextBlock Text="v1.0.0"/></StatusBarItem></StatusBar></Grid></Window>
'@
$reader=New-Object Xml.XmlNodeReader $x;$w=[Windows.Markup.XamlReader]::Load($reader)
foreach($n in 'Tabs','Server','Discover','Path','Browse','AltCred','Prereq','RefreshPre','InstallPre','Analyze','AD','EXO','Results','Summary','Remediation','Report','Archive','Output','Status'){Set-Variable -Scope Script -Name $n -Value $w.FindName($n)}
function Refresh-Views {$Results.ItemsSource=$null;$Results.ItemsSource=@($script:Rows);$Remediation.ItemsSource=$null;$Remediation.ItemsSource=@($script:Rows);$u=@($script:Rows.FailedRecipient|Where-Object {$_}|Sort-Object -Unique).Count;$g=($script:Rows|Group-Object Category|ForEach-Object {$_.Name+': '+$_.Count}) -join ' | ';$Summary.Text='Messages: '+$script:Rows.Count+' | Unique recipients: '+$u+' | '+$g}
function Show-Error($e){[Windows.MessageBox]::Show([string]$e,'IIS SMTP Badmail Analyzer',[Windows.MessageBoxButton]::OK,[Windows.MessageBoxImage]::Error)|Out-Null}
$RefreshPre.Add_Click({try{$Prereq.ItemsSource=@(Get-PrerequisiteState)}catch{Show-Error $_.Exception.Message}})
$InstallPre.Add_Click({$s=$Prereq.SelectedItem;if(-not $s){return};if([Windows.MessageBox]::Show('Install '+$s.Requirement+'?','Confirm',[Windows.MessageBoxButton]::YesNo)-ne 'Yes'){return};try{$Status.Text='Installing...';Install-Prerequisite $s.Requirement;$Prereq.ItemsSource=@(Get-PrerequisiteState)}catch{Show-Error $_.Exception.Message}finally{$Status.Text='Ready'}})
$Discover.Add_Click({try{$script:Server=$Server.Text.Trim();if(-not $script:Server){throw 'Enter an SMTP server.'};if($AltCred.IsChecked){$script:Credential=Get-Credential};$f=@(Find-IisSmtpBadmail $script:Server);if(-not $f.Count){throw 'No IIS SMTP mailroot was discovered. Enter or browse to Badmail manually.'};$Path.Text=$f[0].Badmail;$script:Badmail=$f[0].Badmail}catch{Show-Error $_.Exception.Message}})
$Browse.Add_Click({$d=New-Object Windows.Forms.FolderBrowserDialog;$d.Description='Select IIS SMTP Badmail';if($d.ShowDialog() -eq 'OK'){$Path.Text=$d.SelectedPath}})
$Analyze.Add_Click({try{$Status.Text='Analyzing...';$script:Badmail=$Path.Text.Trim();$script:Server=$Server.Text.Trim();if(-not $script:Server){$script:Server='Unknown'};$script:Rows=@(Invoke-BadmailAnalysis $script:Badmail);Refresh-Views;$Tabs.SelectedIndex=1;Write-AppLog ('Analyzed '+$script:Rows.Count+' messages') 'PASS'}catch{Show-Error $_.Exception.Message}finally{$Status.Text='Ready'}})
$AD.Add_Click({if(-not $script:Rows.Count){return};try{$Status.Text='Validating AD...';Invoke-ADRecipientValidation $script:Rows $script:Credential;Refresh-Views}catch{Show-Error $_.Exception.Message}finally{$Status.Text='Ready'}})
$EXO.Add_Click({if(-not $script:Rows.Count){return};if([Windows.MessageBox]::Show('PowerShell 7 will open for Exchange Online device authentication. Continue?','Exchange Online',[Windows.MessageBoxButton]::YesNo)-ne 'Yes'){return};try{$Status.Text='Validating Exchange Online...';Invoke-EXORecipientValidation $script:Rows;Refresh-Views}catch{Show-Error $_.Exception.Message}finally{$Status.Text='Ready'}})
$Report.Add_Click({if(-not $script:Rows.Count){return};try{$r=Export-AnalyzerReport $script:Rows $script:Server $script:Badmail;$Output.Text='HTML: '+$r.Html+[Environment]::NewLine+'CSV: '+$r.Csv;Start-Process $r.Html}catch{Show-Error $_.Exception.Message}})
$Archive.Add_Click({if(-not $script:Badmail){return};$c=@(Get-ChildItem $script:Badmail -File|Where-Object Extension -in '.BAD','.BDR','.BDP').Count;if([Windows.MessageBox]::Show([string]$c+' files will be COPIED to ZIP. Source files will not be deleted. Continue?','Archive',[Windows.MessageBoxButton]::YesNo,[Windows.MessageBoxImage]::Warning)-ne 'Yes'){return};try{$z=New-BadmailArchive $script:Badmail $script:Server;$Output.Text='Archive: '+$z}catch{Show-Error $_.Exception.Message}})
$Prereq.ItemsSource=@(Get-PrerequisiteState);Write-AppLog 'Application started';[void]$w.ShowDialog()